apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: apiservice
  namespace: family
  labels:
    app: apiservice
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: apiservice