---
apiVersion: v1
kind: Service
metadata:
  name: apiservice
  namespace: family
  labels:
    app: apiservice
spec:
  type: ClusterIP
  ports:
   - port: 8080
     name: apiservice
  selector:
   app: apiservice